name: golangci-lint
on:
  push:
    tags:
      - v*
    branches:
      - master
      - main
  pull_request:
jobs:
  golangci:
    name: gliphook lint and test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: gliphook
    steps:
      - uses: actions/checkout@v2
      - name: mod-get
        run: go mod download
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        env:
          GO111MODULE: on
        with:
          # Required: the version of golangci-lint is required and must be specified without patch version: we always use the latest patch version.
          version: v1.29
          working-directory: gliphook
      - name: Test
        run: go test -v ./...
